<!-- Css Styles -->
<link rel="stylesheet" href="{{url('/landing')}}/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="{{url('/landing')}}/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="{{url('/landing')}}/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="{{url('/landing')}}/css/flaticon.css" type="text/css">
    <link rel="stylesheet" href="{{url('/landing')}}/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="{{url('/landing')}}/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="{{url('/landing')}}/css/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="{{url('/landing')}}/css/magnific-popup.css" type="text/css">
    <link rel="stylesheet" href="{{url('/landing')}}/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="{{url('/landing')}}/css/style.css" type="text/css">